correction dependency check code

diff --git a/ss-tproxy b/ss-tproxy
--- a/ss-tproxy
+++ b/ss-tproxy
@@ -10,6 +10,7 @@ main_conf='/etc/ss-tproxy/ss-tproxy.conf'
 
 function check_command {
     command -v ip      &>/dev/null || { echo "[ERR] Require command not found: 'ip'"        1>&2; exit 1; }
+    command -v netstat &>/dev/null || { echo "[ERR] Require command not found: 'netstat'"   1>&2; exit 1; }
     command -v dnsmasq &>/dev/null || { echo "[ERR] Require command not found: 'dnsmasq'"   1>&2; exit 1; }
     modprobe xt_TPROXY &>/dev/null || { echo "[ERR] Require kmodule not found: 'xt_TPROXY'" 1>&2; exit 1; }
 
@@ -387,7 +388,6 @@ function start {
         echo "# Generated by ss-tproxy at $(date '+%F %T')" >/etc/resolv.conf
         echo "nameserver $dns_direct" >>/etc/resolv.conf
     fi
-    check_command
     start_proxy
     start_resolver
     start_iptables
@@ -506,17 +506,17 @@ EOF
 }
 
 case $1 in
-    start)              start; status;;
-    stop)               stop; status;;
-    status)             status;;
-    r*)                 stop; status; echo; start; status;;
+    start)              check_command; start; status;;
+    stop)               check_command; stop; status;;
+    status)             check_command; status;;
+    r*)                 check_command; stop; status; echo; start; status;;
     show-iptables)      show_iptables;;
     flush-iptables)     flush_iptables;;
-    flush-dnscache)     flush_dnscache;;
     flush-gfwlist)      ipset -F gfwlist &>/dev/null;;
-    update-chnonly)     update_chnonly;;
-    update-gfwlist)     update_gfwlist;;
-    update-chnroute)    update_chnroute;;
+    flush-dnscache)     check_command; flush_dnscache;;
+    update-chnonly)     check_command; update_chnonly;;
+    update-gfwlist)     check_command; update_gfwlist;;
+    update-chnroute)    check_command; update_chnroute;;
     c*)                 check_command;;
     h*)                 help;;
     *)                  help; exit 1;;
