add tls-proxy mode

diff --git a/ss-tproxy b/ss-tproxy
--- a/ss-tproxy
+++ b/ss-tproxy
@@ -37,6 +37,28 @@ case "$mode" in
         command -v chinadns &>/dev/null || { echo "Error: chinadns is not installed." 1>&2; exit 1; }
         command -v curl &>/dev/null || { echo "Warning: curl is not installed." 1>&2; }
         ;;
+    tlspxy_global)
+        modprobe xt_TPROXY &>/dev/null || { echo "Error: xt_TPROXY module is not installed." 1>&2; exit 1; }
+        command -v ip &>/dev/null || { echo "Error: iproute2 is not installed." 1>&2; exit 1; }
+        command -v dnsmasq &>/dev/null || { echo "Error: dnsmasq is not installed." 1>&2; exit 1; }
+        ;;
+    tlspxy_gfwlist)
+        modprobe xt_TPROXY &>/dev/null || { echo "Error: xt_TPROXY module is not installed." 1>&2; exit 1; }
+        command -v ip &>/dev/null || { echo "Error: iproute2 is not installed." 1>&2; exit 1; }
+        command -v dnsmasq &>/dev/null || { echo "Error: dnsmasq is not installed." 1>&2; exit 1; }
+        command -v ipset &>/dev/null || { echo "Error: ipset is not installed." 1>&2; exit 1; }
+        command -v perl &>/dev/null || { echo "Error: perl is not installed." 1>&2; exit 1; }
+        command -v curl &>/dev/null || { echo "Warning: curl is not installed." 1>&2; }
+        command -v base64 &>/dev/null || { echo "Warning: base64 is not installed." 1>&2; }
+        ;;
+    tlspxy_chnroute)
+        modprobe xt_TPROXY &>/dev/null || { echo "Error: xt_TPROXY module is not installed." 1>&2; exit 1; }
+        command -v ip &>/dev/null || { echo "Error: iproute2 is not installed." 1>&2; exit 1; }
+        command -v dnsmasq &>/dev/null || { echo "Error: dnsmasq is not installed." 1>&2; exit 1; }
+        command -v ipset &>/dev/null || { echo "Error: ipset is not installed." 1>&2; exit 1; }
+        command -v chinadns &>/dev/null || { echo "Error: chinadns is not installed." 1>&2; exit 1; }
+        command -v curl &>/dev/null || { echo "Warning: curl is not installed." 1>&2; }
+        ;;
     tproxy_global)
         { command -v ss-redir &>/dev/null || command -v ssr-redir &>/dev/null; } || { echo "Error: ss-redir/ssr-redir is not installed." 1>&2; exit 1; }
         { command -v ss-tunnel &>/dev/null || command -v ssr-tunnel &>/dev/null; } || { echo "Error: ss-tunnel/ssr-tunnel is not installed." 1>&2; exit 1; }
@@ -171,7 +193,7 @@ function update_chnroute {
 
 function flush_cache {
 case "$mode" in
-    *global|*gfwlist*|*chnroute|v2ray*)
+    *global|*gfwlist*|*chnroute|v2ray*|tlspxy*)
         pkill -HUP '^dnsmasq$'
         ;;
     *)
@@ -189,6 +211,9 @@ function start_socks {
 case "$mode" in
 v2ray*)
     eval "$v2ray_runcmd"
+    ;;
+tlspxy*)
+    eval "$tlspxy_runcmd"
     ;;
 tproxy*)
     if [ "$server_use_ssr" = 'false' ]; then
@@ -294,6 +319,74 @@ no-resolv
 port = 53
 server = 127.0.0.1#65353
 $([ -n "$v2ray_server_addr" ] && echo "address = /$v2ray_server/$v2ray_server_addr")
+EOF
+)
+    ;;
+tlspxy_global)
+    if [ $(grep -Ec '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' <<<"$tlspxy_server") -eq 0 ]; then
+        tlspxy_server_addr=$(getent hosts $tlspxy_server | awk '{print $1}' | head -n1)
+    fi
+    dnsmasq -C <(cat <<EOF
+$([ "$dnsmasq_log_on" = 'true' ] && echo 'log-queries')
+log-async = 20
+log-facility = $dnsmasq_log_file
+domain-needed
+cache-size = $dnsmasq_cache_size
+$([ $(dnsmasq --help | grep -c min-cache-ttl) -ne 0 ] && echo "min-cache-ttl = $dnsmasq_cache_time")
+no-negcache
+no-resolv
+port = 53
+server = ${dns_remote/:/#}
+$([ -n "$tlspxy_server_addr" ] && echo "address = /$tlspxy_server/$tlspxy_server_addr")
+EOF
+)
+    ;;
+tlspxy_gfwlist)
+    if [ $(grep -Ec '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' <<<"$tlspxy_server") -eq 0 ]; then
+        tlspxy_server_addr=$(getent hosts $tlspxy_server | awk '{print $1}' | head -n1)
+    fi
+    dnsmasq -C <(cat <<EOF
+$([ "$dnsmasq_log_on" = 'true' ] && echo 'log-queries')
+log-async = 20
+log-facility = $dnsmasq_log_file
+domain-needed
+cache-size = $dnsmasq_cache_size
+$([ $(dnsmasq --help | grep -c min-cache-ttl) -ne 0 ] && echo "min-cache-ttl = $dnsmasq_cache_time")
+no-negcache
+no-resolv
+port = 53
+server = $dns_direct
+$([ -n "$tlspxy_server_addr" ] && echo "address = /$tlspxy_server/$tlspxy_server_addr")
+$(perl -pe "s@^.*+\$@server=/$&/${dns_remote/:/#}\nipset=/$&/gfwlist@" $dnsmasq_gfwlist <(
+perl -ne 'print unless m@^\s|\s\n$|^#|^\d++\.\d++\.\d++\.\d++(?:/\d++)?$@' $dnsmasq_gfwlist_ext
+))
+EOF
+)
+    ;;
+tlspxy_chnroute)
+    chinadns_chnroute_temp=$(mktemp)
+    cat $chinadns_chnroute >$chinadns_chnroute_temp
+    echo "$dns_direct/32" >>$chinadns_chnroute_temp
+    chinadns_params="-b 0.0.0.0 -p 65353 -s $dns_direct,$dns_remote -c $chinadns_chnroute_temp"
+    [ "$chinadns_mutation" = 'true' ] && chinadns_params+=' -m'
+    [ "$chinadns_verbose" = 'true' ] && chinadns_params+=' -v'
+    nohup chinadns $chinadns_params </dev/null &>>"$chinadns_log" &
+
+    if [ $(grep -Ec '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' <<<"$tlspxy_server") -eq 0 ]; then
+        tlspxy_server_addr=$(getent hosts $tlspxy_server | awk '{print $1}' | head -n1)
+    fi
+    dnsmasq -C <(cat <<EOF
+$([ "$dnsmasq_log_on" = 'true' ] && echo 'log-queries')
+log-async = 20
+log-facility = $dnsmasq_log_file
+domain-needed
+cache-size = $dnsmasq_cache_size
+$([ $(dnsmasq --help | grep -c min-cache-ttl) -ne 0 ] && echo "min-cache-ttl = $dnsmasq_cache_time")
+no-negcache
+no-resolv
+port = 53
+server = 127.0.0.1#65353
+$([ -n "$tlspxy_server_addr" ] && echo "address = /$tlspxy_server/$tlspxy_server_addr")
 EOF
 )
     ;;
@@ -652,6 +745,82 @@ function start_rule {
         iptables_intranet_nonstd+=($cidr)
     done
 case "$mode" in
+tlspxy_global|tlspxy_chnroute)
+    iptables -t nat -F PREROUTING
+    iptables -t nat -F POSTROUTING
+    iptables -t mangle -F OUTPUT
+    iptables -t mangle -F PREROUTING
+    iptables -t mangle -F TLSPXY &>/dev/null
+    iptables -t mangle -X TLSPXY &>/dev/null
+
+    iptables -t mangle -N TLSPXY
+    iptables -t mangle -A TLSPXY -d 0/8 -j RETURN
+    iptables -t mangle -A TLSPXY -d 10/8 -j RETURN
+    iptables -t mangle -A TLSPXY -d 127/8 -j RETURN
+    iptables -t mangle -A TLSPXY -d 169.254/16 -j RETURN
+    iptables -t mangle -A TLSPXY -d 172.16/12 -j RETURN
+    iptables -t mangle -A TLSPXY -d 192.168/16 -j RETURN
+    for cidr in "${iptables_intranet_nonstd[@]}"; do
+        iptables -t mangle -A TLSPXY -d $cidr -j RETURN
+    done
+    iptables -t mangle -A TLSPXY -d 224/4 -j RETURN
+    iptables -t mangle -A TLSPXY -d 240/4 -j RETURN
+    iptables -t mangle -A TLSPXY -d $tlspxy_server -j RETURN
+    if [[ "$mode" == *chnroute ]]; then
+        ipset -X chnroute &>/dev/null
+        ipset -R <$iptables_ipset_file
+        iptables -t mangle -A TLSPXY -m set --match-set chnroute dst -j RETURN
+    fi
+    iptables -t mangle -A TLSPXY -j MARK --set-mark $iptables_pbr_fwmark
+
+    iptables -t mangle -A OUTPUT -p tcp -j TLSPXY
+    iptables -t mangle -A OUTPUT -p udp -j TLSPXY
+
+    for intranet in "${iptables_intranet[@]}"; do
+        iptables -t mangle -A PREROUTING -p udp -s $intranet ! -d $intranet --dport 53 -j ACCEPT
+        iptables -t nat    -A PREROUTING -p udp -s $intranet ! -d $intranet --dport 53 -j REDIRECT --to-ports 53
+        iptables -t mangle -A PREROUTING -p tcp -s $intranet -j TLSPXY
+        iptables -t mangle -A PREROUTING -p udp -s $intranet -j TLSPXY
+        iptables -t nat -A POSTROUTING -s $intranet ! -d $intranet -j MASQUERADE
+    done
+
+    iptables -t mangle -A PREROUTING -m mark --mark $iptables_pbr_fwmark -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port ${tlspxy_tcport#*:}
+    iptables -t mangle -A PREROUTING -m mark --mark $iptables_pbr_fwmark -p udp -j TPROXY --on-ip 127.0.0.1 --on-port ${tlspxy_udport#*:}
+
+    ip route add local 0/0 dev lo table $iptables_pbr_number
+    ip rule add fwmark $iptables_pbr_fwmark table $iptables_pbr_number
+    ;;
+tlspxy_gfwlist)
+    iptables -t nat -F PREROUTING
+    iptables -t nat -F POSTROUTING
+    iptables -t mangle -F OUTPUT
+    iptables -t mangle -F PREROUTING
+    iptables -t mangle -F TLSPXY &>/dev/null
+    iptables -t mangle -X TLSPXY &>/dev/null
+
+    ipset -N gfwlist hash:net &>/dev/null
+    perl -ne 'print if m@^\d++\.\d++\.\d++\.\d++(?:/\d++)?$@' $dnsmasq_gfwlist_ext | xargs -n1 ipset -A gfwlist &>/dev/null
+
+    iptables -t mangle -N TLSPXY
+    iptables -t mangle -A TLSPXY -m set --match-set gfwlist dst -j MARK --set-mark $iptables_pbr_fwmark
+
+    iptables -t mangle -A OUTPUT -p tcp -j TLSPXY
+    iptables -t mangle -A OUTPUT -p udp -j TLSPXY
+
+    for intranet in "${iptables_intranet[@]}"; do
+        iptables -t mangle -A PREROUTING -p udp -s $intranet ! -d $intranet --dport 53 -j ACCEPT
+        iptables -t nat    -A PREROUTING -p udp -s $intranet ! -d $intranet --dport 53 -j REDIRECT --to-ports 53
+        iptables -t mangle -A PREROUTING -p tcp -s $intranet -j TLSPXY
+        iptables -t mangle -A PREROUTING -p udp -s $intranet -j TLSPXY
+        iptables -t nat -A POSTROUTING -s $intranet ! -d $intranet -j MASQUERADE
+    done
+
+    iptables -t mangle -A PREROUTING -m mark --mark $iptables_pbr_fwmark -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port ${tlspxy_tcport#*:}
+    iptables -t mangle -A PREROUTING -m mark --mark $iptables_pbr_fwmark -p udp -j TPROXY --on-ip 127.0.0.1 --on-port ${tlspxy_udport#*:}
+
+    ip route add local 0/0 dev lo table $iptables_pbr_number
+    ip rule add fwmark $iptables_pbr_fwmark table $iptables_pbr_number
+    ;;
 tproxy_global*|tproxy_chnroute*|v2ray_global|v2ray_chnroute)
     [[ "$mode" == v* ]] && server_addr=$v2ray_server
     [[ "$mode" == v* ]] && redir_port=${v2ray_redir#*:} || redir_port=60080
@@ -879,6 +1048,9 @@ function start {
 function stop {
     while umount /etc/resolv.conf; do :; done &>/dev/null
 
+    iptables -t mangle -F TLSPXY &>/dev/null
+    iptables -t mangle -X TLSPXY &>/dev/null
+
     iptables -t nat -F OUTPUT
     iptables -t nat -F PREROUTING
     iptables -t nat -F POSTROUTING
@@ -906,13 +1078,10 @@ function stop {
     pkill -9 '^chinadns$'
     pkill -9 '^dnsforwarder$'
 
-    eval "$v2ray_stopcmd" &>/dev/null
-    eval "$socks5_stopcmd" &>/dev/null
-    pkill -9 '^ss-redir$'
-    pkill -9 '^ss-tunnel$'
-    pkill -9 '^ssr-redir$'
-    pkill -9 '^ssr-tunnel$'
-    pkill -9 '^tun2socks$'
+    [[ "$mode" == v2ray_* ]] && eval "$v2ray_stopcmd" &>/dev/null
+    [[ "$mode" == tlspxy_* ]] && eval "$tlspxy_stopcmd" &>/dev/null
+    [[ "$mode" == tun2socks_* ]] && { eval "$socks5_stopcmd" &>/dev/null; pkill -9 '^tun2socks$'; }
+    [[ "$mode" == tproxy_* ]] && { pkill -9 '^ss-redir$'; pkill -9 '^ss-tunnel$'; pkill -9 '^ssr-redir$'; pkill -9 '^ssr-tunnel$'; }
 }
 
 function status {
@@ -939,6 +1108,28 @@ case "$mode" in
         [ $(ss -lnpt | grep ":$rport\s" | wc -l)                -ne 0 ] && echo -e "v2-redir/tcp       \e[32m[running]\e[0m" || echo -e "v2-redir/tcp       \e[35m[stopped]\e[0m"
         [ $(ss -lnpu | grep ":$rport\s" | wc -l)                -ne 0 ] && echo -e "v2-redir/udp       \e[32m[running]\e[0m" || echo -e "v2-redir/udp       \e[35m[stopped]\e[0m"
         [ $(ss -lnpu | grep ":$tport\s" | wc -l)                -ne 0 ] && echo -e "v2-tunnel/udp      \e[32m[running]\e[0m" || echo -e "v2-tunnel/udp      \e[35m[stopped]\e[0m"
+        [ $(pgrep -c '^chinadns$')                              -ne 0 ] && echo -e "chinadns:          \e[32m[running]\e[0m" || echo -e "chinadns:          \e[35m[stopped]\e[0m"
+        [ $(ss -lnp | grep 'dnsmasq' | grep ':53\s' | wc -l)    -ne 0 ] && echo -e "dnsmasq:           \e[32m[running]\e[0m" || echo -e "dnsmasq:           \e[35m[stopped]\e[0m"
+        ;;
+    tlspxy_global)
+        echo "mode:          tlspxy_global"
+        tport=${tlspxy_tcport#*:}; uport=${tlspxy_udport#*:}
+        [ $(ss -lnpt | grep ":$tport\s" | wc -l)                -ne 0 ] && echo -e "tlspxy/tcp         \e[32m[running]\e[0m" || echo -e "tlspxy/tcp         \e[35m[stopped]\e[0m"
+        [ $(ss -lnpu | grep ":$uport\s" | wc -l)                -ne 0 ] && echo -e "tlspxy/udp         \e[32m[running]\e[0m" || echo -e "tlspxy/udp         \e[35m[stopped]\e[0m"
+        [ $(ss -lnp | grep 'dnsmasq' | grep ':53\s' | wc -l)    -ne 0 ] && echo -e "dnsmasq:           \e[32m[running]\e[0m" || echo -e "dnsmasq:           \e[35m[stopped]\e[0m"
+        ;;
+    tlspxy_gfwlist)
+        echo "mode:         tlspxy_gfwlist"
+        tport=${tlspxy_tcport#*:}; uport=${tlspxy_udport#*:}
+        [ $(ss -lnpt | grep ":$tport\s" | wc -l)                -ne 0 ] && echo -e "tlspxy/tcp         \e[32m[running]\e[0m" || echo -e "tlspxy/tcp         \e[35m[stopped]\e[0m"
+        [ $(ss -lnpu | grep ":$uport\s" | wc -l)                -ne 0 ] && echo -e "tlspxy/udp         \e[32m[running]\e[0m" || echo -e "tlspxy/udp         \e[35m[stopped]\e[0m"
+        [ $(ss -lnp | grep 'dnsmasq' | grep ':53\s' | wc -l)    -ne 0 ] && echo -e "dnsmasq:           \e[32m[running]\e[0m" || echo -e "dnsmasq:           \e[35m[stopped]\e[0m"
+        ;;
+    tlspxy_chnroute)
+        echo "mode:        tlspxy_chnroute"
+        tport=${tlspxy_tcport#*:}; uport=${tlspxy_udport#*:}
+        [ $(ss -lnpt | grep ":$tport\s" | wc -l)                -ne 0 ] && echo -e "tlspxy/tcp         \e[32m[running]\e[0m" || echo -e "tlspxy/tcp         \e[35m[stopped]\e[0m"
+        [ $(ss -lnpu | grep ":$uport\s" | wc -l)                -ne 0 ] && echo -e "tlspxy/udp         \e[32m[running]\e[0m" || echo -e "tlspxy/udp         \e[35m[stopped]\e[0m"
         [ $(pgrep -c '^chinadns$')                              -ne 0 ] && echo -e "chinadns:          \e[32m[running]\e[0m" || echo -e "chinadns:          \e[35m[stopped]\e[0m"
         [ $(ss -lnp | grep 'dnsmasq' | grep ':53\s' | wc -l)    -ne 0 ] && echo -e "dnsmasq:           \e[32m[running]\e[0m" || echo -e "dnsmasq:           \e[35m[stopped]\e[0m"
         ;;
