update ss-tproxy.conf

diff --git a/ss-tproxy b/ss-tproxy
--- a/ss-tproxy
+++ b/ss-tproxy
@@ -108,7 +108,13 @@ process_is_running() {
 }
 
 sstproxy_is_started() {
-    iptables -t mangle -nL SSTP_OUTPUT &>/dev/null
+    if is_true "$ipv4"; then
+        iptables -t mangle -nL SSTP_OUTPUT &>/dev/null
+        return $?
+    else
+        ip6tables -t mangle -nL SSTP_OUTPUT &>/dev/null
+        return $?
+    fi
 }
 
 is_ipv4_address() {
@@ -170,6 +176,8 @@ load_config() {
             ;;
     esac
 
+    { is_false "$ipv4" && is_false "$ipv6"; } && log_error "both ipv4 and ipv6 are disabled, nothing to do"
+
     proxy_svraddr4=()
     proxy_svraddr6=()
 
@@ -182,9 +190,11 @@ load_config() {
         fi
     done
 
-    [ "${#proxy_svraddr4[@]}" -eq 0 ] && log_error "there is no ipv4 address in proxy_svraddr"
-    { is_true "$ipv6" && [ "${#proxy_svraddr6[@]}" -eq 0 ]; } && log_error "there is no ipv6 address in proxy_svraddr"
-    { is_false "$ipv6" && [ "${#proxy_svraddr6[@]}" -ne 0 ]; } && log_error "proxy_svraddr contains ipv6 addr, but ipv6 is disabled: ${proxy_svraddr6[@]}"
+    { is_true "$ipv4" && [ "${#proxy_svraddr4[@]}" -eq 0 ]; } && log_error "not found ipv4 address in the proxy_svraddr"
+    { is_true "$ipv6" && [ "${#proxy_svraddr6[@]}" -eq 0 ]; } && log_error "not found ipv6 address in the proxy_svraddr"
+
+    { is_false "$ipv6" && [ "${#proxy_svraddr6[@]}" -ne 0 ]; } && log_warn "found ipv6 address(${proxy_svraddr6[@]}) in the proxy_svraddr, but ipv6 is disabled"
+    { is_false "$ipv4" && [ "${#proxy_svraddr4[@]}" -ne 0 ]; } && log_warn "found ipv4 address(${proxy_svraddr4[@]}) in the proxy_svraddr, but ipv4 is disabled"
 }
 
 check_depend() {
@@ -192,7 +202,8 @@ check_depend() {
     command_is_exists 'ip'       || log_error "command not found: ip"
     command_is_exists 'ipset'    || log_error "command not found: ipset"
     command_is_exists 'dnsmasq'  || log_error "command not found: dnsmasq"
-    command_is_exists 'iptables' || log_error "command not found: iptables"
+
+    is_true "$ipv4" && { command_is_exists 'iptables'  || log_error "command not found: iptables";  }
     is_true "$ipv6" && { command_is_exists 'ip6tables' || log_error "command not found: ip6tables"; }
 
     case "$mode" in
@@ -244,7 +255,7 @@ flush_dnscache() {
 }
 
 flush_gfwlist() {
-    ipset -F gfwlist &>/dev/null || ignore
+    is_true "$ipv4" && ipset -F gfwlist  &>/dev/null || ignore
     is_true "$ipv6" && ipset -F gfwlist6 &>/dev/null || ignore
 }
 
@@ -273,25 +284,22 @@ _flush_iptables() {
 }
 
 flush_iptables() {
-    _flush_iptables "iptables"
+    is_true "$ipv4" && _flush_iptables "iptables"
     is_true "$ipv6" && _flush_iptables "ip6tables"
 }
 
-show_iptables() {
-    printf "\e[36;1m==> iptables-mangle <==\e[0m\n"
-    iptables -t mangle -nvL --line-numbers
+_show_iptables() {
+    printf "\e[36;1m==> $1-mangle <==\e[0m\n"
+    $1 -t mangle -nvL --line-numbers
     echo
-    printf "\e[36;1m==> iptables-nat <==\e[0m\n"
-    iptables -t nat -nvL --line-numbers
+    printf "\e[36;1m==> $1-nat <==\e[0m\n"
+    $1 -t nat -nvL --line-numbers
+}
 
-    if is_true "$ipv6"; then
-        echo
-        printf "\e[36;1m==> ip6tables-mangle <==\e[0m\n"
-        ip6tables -t mangle -nvL --line-numbers
-        echo
-        printf "\e[36;1m==> ip6tables-nat <==\e[0m\n"
-        ip6tables -t nat -nvL --line-numbers
-    fi
+show_iptables() {
+    is_true "$ipv4" && _show_iptables "iptables"
+    { is_true "$ipv4" && is_true "$ipv6"; } && echo
+    is_true "$ipv6" && _show_iptables "ip6tables"
 }
 
 start_dnsserver_gfwlist() {
